HikakuSite/HikakuSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hikaku.urls')),
]

HikakuSite/hikaku/urls.py
from django.urls import path
from . import views

app_name = 'hikaku'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('mypage/', views.MyPage.as_view(), name='mypage'),
    path('search/', views.Search.as_view(), name='search'),
    path('search_result/', views.SearchResult.as_view(), name='search_result'),
    path('offer_list/', views.OfferList.as_view(), name='offer_list'),
]

HikakuSite/hikaku/models.py
from email.mime import image
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ProductModel(models.Model):
  name = models.CharField(verbose_name="商品名", max_length=100, default='')
  price = models.IntegerField(verbose_name="価格", default='')
  image_link = models.TextField(verbose_name="画像リンク", default='')
  
  def __str__(self) -> str:
    return self.name
        
class OfferModel(models.Model):
  product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
  price = models.IntegerField(verbose_name="価格", default='')
  shop = models.CharField(verbose_name="販売店", max_length=100, default='')
  shop_link = models.TextField(verbose_name="ショップリンク", default='')
  
  def __str__(self) -> str:
    return self.shop
  
class BookMarkModel(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
  
  def __str__(self) -> str:
    return  str(self.id)

HikakuSite/hikaku/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm
)


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label 

HikakuSite/hikaku/views/login.py
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from ..forms import LoginForm

class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'hikaku/login.html'

HikakuSite/hikaku/views/logout.py
from django.contrib.auth.views import (
    LoginView, LogoutView
)

class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'hikaku/logout.html'

HikakuSite/hikaku/views/my_page.py
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic
from ..models import BookMarkModel
from django.shortcuts import redirect, render

class MyPage(LoginRequiredMixin, generic.TemplateView):
    template_name = 'hikaku/mypage.html'
    
    def get(self, request, **kwargs):
        bookmark_query = BookMarkModel.objects
        
        # user_idでフィルタ
        user_id = self.request.user.id
        if user_id == None or user_id == "":
            # 検索条件が未指定の場合は全件表示
            bookmark_objects = None
        else:
            bookmark_objects = bookmark_query.filter(user_id=user_id).all()
            
        bookmark_products = []
        for object in bookmark_objects:
            print(type(object.product))
            bookmark_products.append(object.product.name)
            
        context = {
            'username': self.request.user.username,
            'items': bookmark_objects
        }
        return self.render_to_response(context)
    
    def post(self, request, **kwargs):
        user_id = self.request.user.id
        product_id = request.POST["product_id"]
        
        BookMarkModel.objects.filter(user_id=user_id, product_id=product_id).delete()
        
        url = request.get_full_path()
        
        return redirect(url)

HikakuSite/hikaku/views/offer_list.py
from django.views import generic
from ..models import ProductModel, OfferModel, BookMarkModel
from django.shortcuts import redirect, render

class OfferList(generic.TemplateView):
    template_name = 'hikaku/offer_list.html'
    
    def get(self, request, *args, **kwargs):
        offer_query = OfferModel.objects.order_by("price")
        
        # product_idでフィルタ
        product_id = request.GET.get("q")

        if product_id == None or product_id == "":
            offer_objects = None
        else:
            offer_objects = offer_query.filter(product_id=product_id).all()

        # HTMLに出力する内容をセット
        context = {"items": offer_objects}
        
        # HTMLを出力
        return self.render_to_response({"items": offer_objects})

HikakuSite/hikaku/views/search.py
from django.views import generic

class Search(generic.TemplateView):
    template_name = 'hikaku/search.html'

HikakuSite/hikaku/views/search_result.py
from django.views import generic
from functools import reduce
from django.db.models import Q
from ..models import ProductModel, OfferModel, BookMarkModel
from django.shortcuts import redirect, render


class SearchResult(generic.TemplateView):
    template_name = 'hikaku/search_result.html'
    
    def get(self, request, *args, **kwargs):
        product_query = ProductModel.objects.order_by("name")
        # nameでフィルタ
        name = request.GET.get("q")
        if name == None or name == "":
            # 検索条件が未指定の場合は全件表示
            product_objects = product_query.all()
        else:
            product_objects = product_query.filter(name__contains=name).all()
        
        bookmark_query = BookMarkModel.objects
        # user_idでフィルタ
        user_id = self.request.user.id
        if user_id == None or user_id == "":
            # 検索条件が未指定の場合は全件表示
            bookmark_objects = None
        else:
            bookmark_objects = bookmark_query.filter(user_id=user_id).all()
        
        bookmark_id_list = []
        
        if bookmark_objects:
            for object in bookmark_objects:
                bookmark_id_list.append(object.product.id)
        
        # HTMLに出力する内容をセット
        context = {"items": product_objects, 
                   "bookmark_id_list": bookmark_id_list,
                   "record_count": product_objects.count()} # レコード件数
        
        # HTMLを出力
        return self.render_to_response(context)
        
    def post(self, request, **kwargs):
        user_id = self.request.user.id
        product_id = request.POST["product_id"]
        
        model = BookMarkModel(user_id=user_id, product_id=product_id)
        model.save()
        
        url = request.get_full_path()
        
        return redirect(url)

HikakuSite/templates/hikaku/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>価格比較サイト</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'hikaku:search' %}">価格比較サイト</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item mr-auto">
            <a class="nav-item nav-link text-primary" href="{% url 'hikaku:mypage' %}">
              マイページ
            </a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item d-flex align-items-center">
            <span class="nav-item h5 m-auto">{{ user.username }}<span>
          </li>
          <li class="nav-item ml-2">
            <a class="nav-item btn btn-primary" href="{% url 'hikaku:logout' %} " role="button">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'hikaku:login' %}">
              ようこそ、ゲスト！ログインはこちら
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

HikakuSite/templates/hikaku/login.html
{% extends "hikaku/base.html" %}
{% block content %}
<form action="" method="POST">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        {{ form.non_field_errors }}
        {% for field in form %}
          {{ field }}
          {{ field.errors }}
          <hr>
        {% endfor %}
        <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
        <input type="hidden" name="next" value="{{ next }}" />
        {% csrf_token %}
      </div>
    </div>
  </div>
</form>
{% endblock %}

HikakuSite/templates/hikaku/logout.html
{% extends "hikaku/base.html" %}
{% block content %}
<p>ログアウトしました。</p>
{% endblock %}

HikakuSite/templates/hikaku/mypage.html
{% extends "hikaku/base.html" %}
{% block content %}
<main>
  <h1>マイページ</h1>
  <div class="container mt-5">
    <h2>ユーザ情報</h2>
    <div class="row">
      <span class="col col-lg-2">姓:</span>
      <span class="col">{{ user.first_name }}</span>
    </div>
    <div class="row">
      <span class="col col-lg-2">名:</span>
      <span class="col">{{ user.last_name }}</span>
    </div>
    <div class="row">
      <span class="col col-lg-2">ユーザ名:</span>
      <span class="col">{{ user.username }}</span>
    </div>
    <div class="row">
      <span class="col col-lg-2">email:</span>
      <span class="col">{{ user.email }}</span>
    </div>
  </div>
  <div class="container mt-5">
    <h2>お気に入り商品</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">画像</th>
          <th scope="col">商品名</th>
          <th scope="col">価格</th>
          <th scope="col">お気に入り</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <form action="{% url 'hikaku:mypage' %}" method="POST">
        {% csrf_token %}
        <tr>
          <th scope="row"><img src={{ item.product.image_link }}></th>
          <td><a href="../offer_list/?q={{ item.product.id }}"> {{ item.product.name }}</a></td> 
          <td>{{ item.product.price }}</td>
          <td>
            <input type="hidden" name="product_id" value={{ item.product.id }}>
            <button type="submit" class="btn btn-info">お気に入り削除</button>
          </td>
        </tr>
        </form>
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

HikakuSite/templates/hikaku/offer_list.html
{% extends "hikaku/base.html" %} 
{% load render_table from django_tables2 %} 
{% block content %}
<main>
  <h1>検索結果</h1>
  <div class="container">
    <form id="main-form" class="form-horizontal" role="form" method="GET">
      {% csrf_token %}
      <div class="control-label">商品数:{{ record_count }}</div>
      <div
        class="
          table table-hover table-header-checkbox-hidden
          syuppin-item-table
          sticky-table
          mt-2
        "
      >
        <table class="table">
          <thead>
            <tr>
              <th scope="col">価格</th>
              <th scope="col">ショップ</th>
              <th scope="col">ショップサイト</th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
            <tr>
              <th scope="row">{{ item.price }}円</th>
              <td>{{ item.shop }}</td>
              <td><a href={{ item.shop_link }} class="btn btn-primary">ショップの売り場へ行く</a> </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </form>
  </div>
</main>
{% endblock %}

HikakuSite/templates/hikaku/price_list.html
{% extends "hikaku/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
<main>
    <h1>検索結果</h1>
    <div class="container">
        <form id="main-form" class="form-horizontal" role="form" method="GET">
            {% csrf_token %}
            <div class="table table-hover table-header-checkbox-hidden syuppin-item-table sticky-table mt-2">
                {% render_table table %}
            </div>
        </form>
    </div>
</main>
{% endblock %}

HikakuSite/templates/hikaku/search.html
{% extends "hikaku/base.html" %} {% block content %}
<main>
  <h1>価格検索</h1>
  <form action="{% url 'hikaku:search_result' %}" method="GET">
    <div class="ui action input" style="width: 100%">
      <input type="text" placeholder="価格検索" name="q" />
      <span class="input-group-btn">
        <button type="submit" class="btn btn-primary">検索</button>
      </span>
    </div>
  </form>
</main>
{% endblock %}

HikakuSite/templates/hikaku/search_result.html
{% extends "hikaku/base.html" %} 
{% load render_table from django_tables2 %} 
{% block content %}
<main>
  <h1>検索結果</h1>
  <div class="container">
    <div class="control-label">商品数:{{ record_count }}</div>
    <div
      class="
        table table-hover table-header-checkbox-hidden
        syuppin-item-table
        sticky-table
        mt-2
      "
    >
      <table class="table">
        <thead>
          <tr>
            <th scope="col">画像</th>
            <th scope="col">商品名</th>
            <th scope="col">価格</th>
            <th scope="col">お気に入り</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
          <form action="{{ request.get_full_path }}" method="POST">
          {% csrf_token %}
          <tr>
            <th scope="row"><img src={{ item.image_link }}></th>
            <td><a href="../offer_list/?q={{ item.id }}"> {{ item.name }}</a></td> 
            <td>{{ item.price }}</td>
            {% if request.user.is_authenticated and item.id not in bookmark_id_list %}
            <td>
              <input type="hidden" name="product_id" value={{ item.id }}>
              <button type="submit" class="btn btn-info">お気に入り追加</button>
            </td>
            {% else %}
            <td><button type="submit" class="btn btn-info" disabled>お気に入り追加</button></td>
            {% endif %}
          </tr>
          </form>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}